import type { Metadata } from 'next';
import { Figtree } from 'next/font/google';
import './globals.css';
import { Providers } from '@/components/providers';
import { ThemeProvider } from '@/components/theme-provider';
import Navigation from './navigation';

const figtree = Figtree({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang='en' suppressHydrationWarning>
            <body className={`${figtree} font-sans text-[0.900rem]/[1.35rem] antialiased`}>
                <ThemeProvider
                    attribute='class'
                    defaultTheme='system'
                    enableSystem
                    disableTransitionOnChange>
                    <Navigation />
                    <Providers>{children}</Providers>
                </ThemeProvider>
            </body>
        </html>
    );
}
